### ISSUE TITLE
MBTiles tile images seem to be cached until app restart when switching layer list check on/off

### ISSUE THREAD

**Issue by sanak** [geopaparazzi/smash#112]
~~This issue was also reported on Facebook group recently.~~
~~I will take some screenshots about this for more details, tomorrow.~~

Here are reproducible datasets around initial location Bolzano-Bozen zoom level 10-16.
- [admin_bound.mbtiles.zip](https://github.com/moovida/smash/files/6196638/admin_bound.mbtiles.zip)
- [building.mbtiles.zip](https://github.com/moovida/smash/files/6196642/building.mbtiles.zip)

And here are the images (2nd shows just switch on/off example):
![Screenshot_20210324-125822](https://user-images.githubusercontent.com/629923/112302361-5add1a00-8cde-11eb-9d45-70b14ea688e5.jpg) ![Screenshot_20210324-122102](https://user-images.githubusercontent.com/629923/112302380-5fa1ce00-8cde-11eb-9fe3-1113659a65f7.jpg)

I created the MBTiles from QGIS 3.16 (LTS) QMetaTile plugin, so I also upload QGIS project file (*.qgs), original downloaded GeoJSON files from Overpass Turbo and QMetaTile plugin setting image (for admin_bound.geojson).
- [bolzano-bozen.qgs.zip](https://github.com/moovida/smash/files/6196695/bolzano-bozen.qgs.zip)
- [admin_bound.geojson.zip](https://github.com/moovida/smash/files/6196697/admin_bound.geojson.zip)
- [building.geojson.zip](https://github.com/moovida/smash/files/6196699/building.geojson.zip)

![qmetatiles_admin_bound](https://user-images.githubusercontent.com/629923/112303013-2453cf00-8cdf-11eb-9900-69a57a76a4a3.png)

**Comment by moovida** [comment]
Hi, this should be now solved, with the upgrade to the new flutter_map libs.
