### ISSUE TITLE
Polygons not rendered when added

### ISSUE THREAD

**Issue by frafra** [geopaparazzi/smash#117]
Hi!
I have a PostGIS layer with some features. Such layer has been created by importing a geopackage I created previously. Smash is able to load it and to make changes, but when I try to add a new polygon, the small triangle is not shown on the map, but it is saved in the database. If I close and open SMASH again I can see the added polygons.

SMASH is running on Android, version 1.6.4.

**Comment by moovida** [comment]
oh, that sounds like a bug. Will have to check that.

**Comment by moovida** [comment]
This shoulsd be solved now. If not, feel free to reopen it.
