### ISSUE TITLE
Camera Settings

### ISSUE THREAD

**Issue by mbasa** [geopaparazzi/smash#123]
Hi. 

Is the Settings -> Camera resolution options functional already? Can't seem to find any reference to it in `camera.dart` of smashlibs. 

Thanks.

**Comment by mbasa** [comment]
@moovida  Is it possible to add a `imageQuality` value as well in the `picker.getImage` call.  As in Low -> 600, etc. 

Thanks a lot.

**Comment by mbasa** [comment]
Actually I am not sure. I just know this: 

```
imageQuality: value ranges from 0-100, where 100 is max/original quality. If it’s null, the original quality returned.
```

**Comment by moovida** [comment]
Hi @mbasa , I added this now and would appreciate fi you could see if it works for you.

Basically is the setting is set:
```
GpPreferences().setString(SmashPreferencesKeys.KEY_CAMERA_RESOLUTION, CameraResolutions.MEDIUM);
```
the Camera will use it HIGH=100, MEDIUM=80, LOW=60.

**Comment by mbasa** [comment]
Thanks. Will test it out.
