### ISSUE TITLE
Delete existing features not works

### ISSUE THREAD

**Issue by pierluigiderosa** [geopaparazzi/smash#125]
In geopackage layer when you are in editing session and the polygon is highlighted the _button trash in present but it does not work_. If you press the button trash it seems that the **button is inactive**.

**Comment by moovida** [comment]
Hi @pierluigiderosa , I just notice that there is an imperfection in the documentation here: https://www.geopaparazzi.org/smash/index.html#_delete_existing_features

To delete a feature, you need to long tap the trash icon. This is in order to avoid to remove data due to unwanted touches.
