### ISSUE TITLE
Label points using form fields

### ISSUE THREAD

**Issue by frafra** [geopaparazzi/smash#128]
Points registered in SMASH from the same form all look the same at the moment. It could be useful to show a different label based on a specified form field.

For example, we could have an attribute named `sectionitemname` refers to the value of one of the `key` attributes:

```json
[
  {
    "sectionname": "mysection",
    "sectiondescription": "mydescription",
    "sectionitemname": "specie",
    "forms": [
      {
        "formname": "specie",
        "formitems": [
          {
            "key": "specie",
            "values": {
              "items": [
                { "item": "ctenocephalides felis" },
                { "item": "bradysia impatiens" },
                { "item": "ctenolepisma longicaudata" }
              ]
            },
            "value": "",
            "type": "autocompletestringcombo"
          }
        ]
      }
    ]
  }
]
```

In this case, if a user saves a point after selecting `ctenocephalides felis`, then such value would be shown in the map right under the pinpoint.

What do you think about such feature?

**Comment by moovida** [comment]
Hi @frafra , just arrived back from vacation, catching up slowly.

If you add to a formitem the islabel tag, it will be used. Example:

```
{
    "sectionname": "text note",
    "sectiondescription": "a simple text note",
    "sectionicon": "fileAlt",
    "forms": [
      {
        "formname": "text note",
        "formitems": [
          {
            "key": "title",
            "value": "",
            "icon": "font",
            "islabel": "true",
            "type": "string",
            "mandatory": "no"
          },
          {
            "key": "description",
            "value": "",
            "icon": "infoCircle",
            "type": "string",
            "mandatory": "no"
          }
        ]
      }
    ]
  },
```

Is this what you are looking for?

**Comment by moovida** [comment]
Closing this for now assuming that is what you where looking for :-) Feel free to reopen it.

**Comment by frafra** [comment]
Sorry for my late reply, I am on vacation :) Thank you!

**Comment by moovida** [comment]
Enjoy @frafra! That gives me more time with the issues :-D, good
