### ISSUE TITLE
Adding new key:value to note.form

### ISSUE THREAD

**Issue by mbasa** [geopaparazzi/smash#133]
I am adding a new key:value into the **note.form** programmatically which will contain the Redmine Issue ID after a successful export. The reason for this is to update the Redmine Issue whenever a SMASH Form has been edited.  Right now, a new Redmine issue is created whenever there is a SMASH Form edit. 

Just like to get your opinion if this will be alright and if adding a new key:value might cause problems in the future. Code is below: 

```dart
  Map<String, dynamic> noteForm = jsonDecode(note.form);
  noteForm["gtt_issue_id"] = issueId;

  note.form = jsonEncode(noteForm);
  note.timeStamp = DateTime.now().millisecondsSinceEpoch;

   await db.updateNote(note);
   noteUpdated = true;

  ---
  ---
  ---

  if (noteUpdated) {
      ProjectState projectState =
          Provider.of<ProjectState>(context, listen: false);

      projectState.reloadProject(context);
    }
```

Regards, 

Mario.

**Comment by dkastl** [comment]
This might be an alternative solution for custom forms:
https://github.com/gtt-project/redmine_gtt_smash/issues/28
(it will not work for simple notes)

**Comment by mbasa** [comment]
Please disregard this issue since I now add the issueId in the formitems:

```dart
          List<Map<String, dynamic>> fi = List<Map<String, dynamic>>.from(
              noteForm["forms"][0]["formitems"]);

          List<Map<String, dynamic>> formItems =
              GttUtilities.addIssueToFormItems(fi, issueId);

          noteForm["forms"][0]["formitems"] = formItems;

          note.form = jsonEncode(noteForm);
          ---
          ---
          ---
```

```dart
  static List<Map<String, dynamic>> addIssueToFormItems(
      List<Map<String, dynamic>> formItems, int issueId) {
    bool issueExists = false;

    for (Map<String, dynamic> f in formItems) {
      if (f["key"] == "issue_id") {
        issueExists = true;
      }
    }

    if (!issueExists) {
      Map<String, dynamic> map = {
        "key": "issue_id",
        "label": "",
        "value": "$issueId",
        "values": null,
        "type": "hidden",
        "mandatory": "yes",
      };
      formItems.add(map);
      debugPrint("*** added issue_id into map ***");
    }
    return formItems;
  }

```

**Comment by moovida** [comment]
Hi @mbasa , can you confirm the hidden works properly also in SMASH? I was allocating time to double check that, but if you tell me you tested it, I am more than happy. 
Also I confirm that a hidden field should be the way to go.

**Comment by mbasa** [comment]
It works properly for us. We have been including Redmine's project_id, tracker_id, etc. as `hidden` in the Forms and have not encountered any problems as of now.
