### ISSUE TITLE
Automatic zoom level too low to distinguish between close points 

### ISSUE THREAD

**Issue by frafra** [geopaparazzi/smash#134]
Hi! :)
When I add 2 notes in the same position and I move outside the area, I can click on a circle which includes both points, similar to this: `(2)`. If I click on it, the map is panned and zoomed, but the zoom is not sufficient to distinguish between the two points. Zooming in twice by clicking on the `+` zoom button twice :mag: makes it possible to see the two points.

Possible solution: when clicking on a group of points, get the bounding box of that cluster, and do a pan+zoom of that bounding box, instead of doing that for a specific point.

**Comment by moovida** [comment]
For now I tried to solve this the simple way, by changing some cluster parameters and allowing for higher zoomlevels even when the maps do not support it.

Feel free to open this up again if that doesn't work well :-)
