### ISSUE TITLE
Clicking on a new note, should close previously opened popups

### ISSUE THREAD

**Issue by frafra** [geopaparazzi/smash#135]
Hi again :)
When I click on a note, I get some basic details (latitude, longitude, altitude, timestamp) inside a popup, which disappears after ~5 seconds. If I click on another note, while the previous popup is still open, nothing happens apparently, but when the first popup automatically closes, the second one opens. This behavior can be a bit misleading.

I suggest that opening a note should close existing popups.
Closing popups automatically after can also be reconsidered in my opinion (there is a `x` close button to close the popup).

**Comment by frafra** [comment]
I would add that popups should also be closed when a note is modified. Example:

1. Create note A
2. Create note B
3. Click on note A
4. Click on note B
5. Modify note A (popup A is still shown)
6. Popup B is shown over the form

**Comment by moovida** [comment]
fixed
