### ISSUE TITLE
vector editing in Smash 1.70

### ISSUE THREAD

**Issue by talllons** [geopaparazzi/smash#145]
Hi,
with the latest release of smash (.7.0), when I try to create lines and polygons in the geopackages, when I select the newly created geometry to start editing, the app crashes showing a gray screen. The problem occurred using different devices with different Android versions (9 and 11). I haven't checked if the same problem also occurs for points. 

Sergio

**Comment by moovida** [comment]
Hi @talllons , thanks for the report and sorry for the late reply. 
I have been able to reproduce the issue and am looking into it.

**Comment by moovida** [comment]
This should be solved now.
