### ISSUE TITLE
simplifying points

### ISSUE THREAD

**Issue by killerm250m** [geopaparazzi/smash#146]
I am wondering where is the best place to do polygon/polyline points simplification, I want to keep it clean as possible.

**Comment by moovida** [comment]
What do you mean exactly? Simplify shapes for faster rendering?

For reference, there is this package that can be used: https://pub.dev/packages/simplify_dart
or, clearly, it would be great to port the DouglasPeuckerSimplifier from JTS to dart_jts, depending on your needs.

**Comment by killerm250m** [comment]
Yes, simplifying shapes.
I have already ported and used DouglasPeuckerSimplifier but not in dart_jts

**Comment by moovida** [comment]
Simplification doesn't make sense in SMASH directly. To apply it to rendered shapes, you need to bring it into the flutter_map project. Only in there the conversion to screen occurs and you are able to handle it based on the zoom level. But in any case the package above should be faster. 
I did a test in flutter_map back then , but then I wasn't able to supply a PR and things changed a lot a meanwhile.
Try to get in touch with the flutter_map community.

**Comment by killerm250m** [comment]
Oh okay thanks
