### ISSUE TITLE
Supporting WFS-T

### ISSUE THREAD

**Issue by killerm250m** [geopaparazzi/smash#148]
I am wondering how to add QGIS/ARCGIS as feature layers ?

**Comment by moovida** [comment]
What exactly do you mean by QGIS/ARCGIS layers?
SMASH supports Geopackage and Shaepfile (readonly).

**Comment by killerm250m** [comment]
I mean adding vector layer like [this]( https://www.arcgis.com/home/webmap/viewer.html?url=https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/Florida_housing_by_census_tract/FeatureServer&source=sd)

**Comment by killerm250m** [comment]
For more clifrication 
![242006816_4322960597809719_4424766978932704524_n](https://user-images.githubusercontent.com/24648104/133791046-32bc1119-886e-43a5-9da5-6d1fe967be63.jpg)

**Comment by killerm250m** [comment]
for more clarification

![Capture](https://user-images.githubusercontent.com/24648104/133791185-1839b61f-2e95-4cfd-a543-56db35ce43b6.PNG)

**Comment by frafra** [comment]
> I mean adding vector layer like [this](https://www.arcgis.com/home/webmap/viewer.html?url=https://services.arcgis.com/V6ZHFr6zdgNZuVG0/ArcGIS/rest/services/Florida_housing_by_census_tract/FeatureServer&source=sd)

That is a map from a website, not a file like a GeoPackage or a Shapefile. It doesn't really matter if it is shown by arcgis.com or another website, you still need a file. To add such vector to SMASH, you should download it first.

**Comment by killerm250m** [comment]
So there is no way to add a vector layer without depending on GeoPackage, I want to change from GeoPackage because I want to sync my vector layers back to server.

**Comment by moovida** [comment]
So you mean WFS, and moreover the transactional version. There is currently no implementation in flutter for that. I wish there was one.
I think your best bet is to enhance the current PostGIS support. That works directly on the server. But it is a simple and plain test. It needs to be connected.

**Comment by killerm250m** [comment]
So you mean by enhancing the already implemented PostGIS support I can use WFS?

**Comment by moovida** [comment]
No, PostGIS would be an alternative. 
Implementing a WFS-T client is quite some work I think.

There is an implementation in leaflet: https://github.com/respec/leaflet.wfs-t
that might be placed as flutter_map plugin I think. And if you do that, you sure get the hero of many in the communitiy :-)

**Comment by killerm250m** [comment]
Can I use the same flow GeoPackage used to create WFS plugin? I mean if there is anything that is already made that helps as a starting point.

**Comment by moovida** [comment]
For Geopackage and Postgis I followed the same flow. If you are going to implement the WFS-T plugin part, I will sure support you in the SMASH part and if necessary we can change the workflow to have a better abstraction.

**Comment by killerm250m** [comment]
Will I consider offline storage SQLite?

**Comment by moovida** [comment]
yes, or well, I would use Geopackage (which again is sqlite), because it gives you the possibility to insert feature tables and use the spatial indexes.

**Comment by killerm250m** [comment]
So you mean if I implement the WFS plugin correctly I can use the GeoPackage features?

**Comment by moovida** [comment]
If you use WFS for simple features yes. WFS can also have a very complex schema, but that is usually not something that is exposed for mobil editing. I am assuming also the leaflet wfs-t plugin works with simplefeatures.
In SMASH up to now I have been using the EditableQueryResult to hold simple features information from databases. It is really simple though, you might need something more in future.

**Comment by killerm250m** [comment]
Yes, all my use cases are simple features, before I start working on the plugin I want to ask some questions :

1. Should I use it as a plugin, or like GeoPackage /shapefile structure.
2. How do I save layers into storage (assuming I get the data from WFS how do I save the data as GeoPackage ? ).
3. How I will deal with edits in offline/online status.

**Comment by killerm250m** [comment]
For a temporary solution, I  converted the WFS layer to GeoPackge using the ogr2ogr library, this should be done on the back-end, at the current time it supports many languages.
go [here](https://gdal.org/programs/ogr2ogr.html) for more information

**Comment by moovida** [comment]
Yes that is sure a good solution of your backend takes care of synching the geopackage back into the central database.
