### ISSUE TITLE
Showing vector layers based on zoom level

### ISSUE THREAD

**Issue by killerm250m** [geopaparazzi/smash#150]
I have a situation where I want to show a large number of layers (from the GeoPackge file) so it's not feasible to show them all at once, so is there is an attribute that can help me to know the min/max zoom for a particular layer?

**Comment by moovida** [comment]
I am afraid not. the geopackage format is seen as an external format, so there has never been an idea of creating custom fields.
This could be something that finds its place in the layer style. SLD has support for that. So I assume that would be the right place.

**Comment by killerm250m** [comment]
Thank you very much @moovida.
