### ISSUE TITLE
delete labels while uploading to gss?

### ISSUE THREAD

**Issue by malfino** [geopaparazzi/smash#156]
Hello,

I've spent quite some time to figure this out, but I didn't find it. Maybe it's a feature request...

I can delete a label in the app smash, but once I press export, the deletion will not be exported to the gss. So this leads me with a situation, that I can never ever remove a label from the central storage in gss. Neither with the app nor with with gss-web-interface. 
What I do is, that I rename/recolor the labels to create a ignore flag instead of deleting. Is there a way to upload the deletion information through the export-function?

thanks

**Comment by moovida** [comment]
Hi @malfino , I am not sure I understand. What do you mean by "delete label" of a note? Change the json to set the **isLabel** to false or remove it?
Are you talking about simple or form notes?

**Comment by moovida** [comment]
On the server from next release on, there is the possibility to delete notes. Closing this here.
