### ISSUE TITLE
Exported image folder is empty

### ISSUE THREAD

**Issue by silviafranceschi** [geopaparazzi/smash#158]
The exported image folder is empty.

**Comment by talllons** [comment]
I was about to make the same report but Silvia preceded me. I was able to recover the photos of a Smash project (form notes and not simple notes that works well) only by loading it in Geopaparazzi and then exporting them. 
Cheers
Sergio

**Comment by moovida** [comment]
This is due to the fact that only simple images are exported and not also those of the forms. 

changed this behavior to export all images available.
