### ISSUE TITLE
.GPAP file: images table "lat" and "lon" fields using the note's lat and lon values

### ISSUE THREAD

**Issue by theARAking** [geopaparazzi/smash#168]
Hi,

The "lat" and "lon" fields of the images table use the lat and lon values from the note that the image is a part of. This means that if the note is started in one place and the user moves before taking the picture, the lat & lon of the image in the images table does not use the lat & lon of where the image was taken, but rather, where the note was started.

In Geopaparazzi, the lat and lon values are from where the picture was taken. Would it be possible to have the lat & lon function this way in SMASH? It would greatly help for our projects.

Thank you for your work on SMASH and consideration.

**Comment by moovida** [comment]
Hi @theARAking thanks for this report. 
I will investigate this, since it makes sense as it was in geopaparazzi. Will report back here.

**Comment by moovida** [comment]
This should be fixed now.

**Comment by theARAking** [comment]
That's great! Thanks!
