### ISSUE TITLE
Measure tool issue

### ISSUE THREAD

**Issue by colla70** [geopaparazzi/smash#175]
'measure tool' activated (icon turn to red)--> drawing with finger only pan the map (as the tool was not active).
Two fingers touch at the same time (as pinch to zoom) sometimes measures the distance between, dragging sums measures between fingers on map, leaving a finger measure start as expected.
Tried on Samsung A20 and on Lenovo Tab M10, SMASH 1.7.2

**Comment by colla70** [comment]
Hi @moovida , yes I can test it.

**Comment by moovida** [comment]
Great, here you go @colla70 : https://we.tl/t-mFLH1Sawwx

**Comment by colla70** [comment]
Tested on Lenovo Tab M10 and it works as expected.
Thanks.

**Comment by moovida** [comment]
That is great to hear, thanks.
