### ISSUE TITLE
App stops logging after 5 minutes when running in background

### ISSUE THREAD

**Issue by Maikel86** [geopaparazzi/smash#179]
I have been testing the app on an Android phone for a few months, and while it is great, there's something that is really stopping me from using it more widely.

When I enable logging a track and lock phone, the app is supposed to keep registering the track on the background. I have all the permissions enabled to allow this to happen. However the track only gets registered for the first 5 minutes of the phone's screen being locked. The permanent notification keeps saying "logging", but if I return to the app, one can see that it stopped logging at some point and a straight line will show from the last position to my current position.

The app is supposed to be working in the background but it doesn't after a few minutes of locking the screen.
![IMG_20220409_100427](https://user-images.githubusercontent.com/8950873/162563293-d6054c26-d887-4518-883a-5b44caa1ca91.jpg)
![IMG_20220409_100604](https://user-images.githubusercontent.com/8950873/162563295-0bb45b2a-eda5-4581-9337-692708888d60.jpg)
![IMG_20220409_102432](https://user-images.githubusercontent.com/8950873/162563347-8abbc086-e676-4591-b0cb-6cdf858a777b.jpg)

**Comment by Maikel86** [comment]
![IMG_20220409_102710](https://user-images.githubusercontent.com/8950873/162563496-6f712ff6-534a-4336-a650-eff2ec9cec0a.jpg)

**Comment by moovida** [comment]
Hi @Maikel86 , the only thing I can think of is that battery optimization is enabled for smash.
Can you check if that is the case? On some phones it might behave more aggressively and block the background gps.

**Comment by Maikel86** [comment]
Hi @moovida, this resolved the issue. The battery saver for SMASH needs to be set to "No restrictions".

![IMG_20220410_210758](https://user-images.githubusercontent.com/8950873/162782576-81c4b95a-f034-4a54-a490-f51bc6a784cf.jpg)

Thanks a lot!

**Comment by moovida** [comment]
Great to hear!
