### ISSUE TITLE
Binary of smash is not Free Software and cannot be copied

### ISSUE THREAD

**Issue by gdt** [geopaparazzi/smash#183]
See #182, which points out that the built apk includes `com/google/firebase` and `com/google/android/gms`.   These are not Free Software, and thus people can't copy the apk while complying with the GPL3 terms of smash.    Even if there is a build favor `Free` that omits them for f-droid, I think this is still a bug for them to ever be included.

I realize it's probably not that easy to fix.

**Comment by moovida** [comment]
Moved discussion and updates to #182
