### ISSUE TITLE
"flutter pub get" failed on M1 Mac + Flutter 3 environment

### ISSUE THREAD

**Issue by sanak** [geopaparazzi/smash#186]
Because my main personal PC (Intel MacBook Pro) crashed at a day before yesterday, I am setting up M1 MacBook Pro from company with Flutter 3 (without Rosetta), but I encountered the following error, when running `flutter pub get` on my new local environment.
```
% cd /path/to/smash
% flutter clean
% flutter pub get
Because dart_jts >=0.0.7+2 depends on collection >=1.14.13 <=1.15.0 and every version of flutter_localizations 
from sdk depends on collection 1.16.0, dart_jts >=0.0.7+2 is incompatible with flutter_localizations from sdk.
So, because smash depends on both flutter_localizations from sdk and dart_jts ^0.2.0, version solving failed.
Running "flutter pub get" in smash...                                   
pub get failed (1; So, because smash depends on both flutter_localizations from sdk and dart_jts ^0.2.0, version
solving failed.)
```

It would be nice to support new Flutter 3 environment.

**Comment by sanak** [comment]
@moovida (CC: @mbasa, @nobnisai, @dkastl)
Thanks for a big update!
I confirmed that the latest Flutter 3.3.1 works well on `master` branch, so I close this issue.
(I found that some Japanese translation is missing, so we may create another PR for that in this week.)

**Comment by moovida** [comment]
Thanks for confirming it also works for you. It was indeed a big set of changes to make everything null safe. 
There will be little issues for a while I think, so let's keep our eyes open and test a lot. :-) 
I will do some more enhancements, and then asap make a release, which will then contain also your plugin.
