### ISSUE TITLE
Import/Export plugin's localization seems not to work

### ISSUE THREAD

**Issue by sanak** [geopaparazzi/smash#194]
@moovida @mbasa (CC: @dkastl, @nobnisai)
I am trying to check Import/Export plugin's Japanese localization, but it seems not to work correctly, and I guess that current localization library (`flutter_intl` by Localizely) may not support multi libraries (like `SL` and `IEL`) localization (or needs something additional process).

To make sure about this, I created the PR #193 which removed import/export localization keys/values from `lib/l10n/intl_*.arb` and generated `l10n.dart` and `intl/messages_*.arb`.

So, could you try the PR's branch, when you have a time ?

Here are details about my environment:
- OS: M1 Mac 12.6 (Moterey)
- Flutter: 3.3.1
- Dart: 2.18.0
- Android Studio: Dolphin 2021.3.1
  - Plugins:
    - Dart: 213.7371 JetBrains
    - Flutter: 70.0.3 flutter.dev
    - Flutter Intl: 1.17.3-2020.3 Localizely

**Comment by moovida** [comment]
Hi @sanak , I am testing your branch on smash (without changing the import/export plugin).
I set my phone to italian to see if labels are properly taken.

In the GTT plugin settings I find a: "URL del server", which is  an Italian label. But then there are many other labels that are not translated, so I am not sure.

Is that enough for a test?

**Comment by sanak** [comment]
@moovida Thanks for quick check and sorry for not mentioning reproducible steps.

On my environment, I checked that `Import` screen's GSS description localization.
![Screenshot_20220919-182806](https://user-images.githubusercontent.com/629923/190988997-bc555fc0-f255-4c83-a5c6-ae00afa2b650.png)

It should be Italian label on your environment, but if it's not reproducible on your environment, the cause may be my local develop environment...

**Comment by moovida** [comment]
@sanak , if you enter the setting, do you see Italian labels?

I see the import screen same as you do. It might just be that the labels are missing? Will check

**Comment by sanak** [comment]
@moovida 
> @sanak , if you enter the setting, do you see Italian labels?

Yes, I could see Japanese labels on my Android phone.
![Screenshot_20220919-185214](https://user-images.githubusercontent.com/629923/190992976-263ff652-f3a4-4d4c-9cf2-b98ba3ad1600.png)

And the reason why the setting screen is no problem is that I seem to forget to remove the keys on the PR branch...
https://github.com/gtt-project/smash/blob/remove-import-export-messages-from-intl/lib/l10n/intl_en.arb#L707-L714

Those are duplicated on smash_import_export_plugins side, so I will delete those also on the PR branch.
https://github.com/geopaparazzi/smash_import_export_plugins/blob/master/lib/l10n/intl_en.arb#L107-L114

**Comment by sanak** [comment]
I forgot to paste the debug screen capture, but `IEL.getDescription` seems to pick from `SL` messages (from `flutter_intl` global cache), so that may be the cause of this issue.
```dart
  @override
  String getDescription() {
    return IEL.of(context).importWidget_importFromGeopaparazzi;
  }
```
![flutter-intl-pick-cache](https://user-images.githubusercontent.com/629923/190994216-0f4b8d02-9d08-42d6-8c29-96ae8be2f603.png)

**Comment by moovida** [comment]
Hi @sanak , I am afraid vscode support for language is not all that good. I somehow thought it would just work. But the duplication of the strings... I should have known better.

I do not have much time to investigate it in this week, but if you come up with a solution, I will sure support you. Please keep us updated.

**Comment by sanak** [comment]
@moovida
> I do not have much time to investigate it in this week, but if you come up with a solution, I will sure support you. Please keep us updated.

Okay, thanks.
I will ask this in our internal team at first.

**Comment by sanak** [comment]
@moovida Thanks for merging the set of PRs ! 🙇👍

**Comment by moovida** [comment]
Thanks for the work @sanak :-) 
Everything seems to work right now.
