### ISSUE TITLE
Prepare project for translation

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/smash#2]
Prepare project for translation

**Comment by dkastl** [comment]
Looked at Transifex and didn't find anything. Then I found this issue ;-)
Is this something to help with? It probably requires some coordination.

**Comment by moovida** [comment]
Hi @dkastl , we planned to make the project fix for translations by the end of the year/begin new year.

We were trying to understand if the project would get some traction in the shadow of geopaparazzi.
It looks like it could make it and for us it is way simpler to develop than geopaparazzi.

There is some code work to do to make smash translation fit, so it will take me some time. 
I will keep this issue updated.

**Comment by dkastl** [comment]
Well, speaking from the Japanese perspective the lack of iOS support in Geopaparazzi was a real problem here. And we have done some Flutter apps recently, so this makes contributing easier.

I'm currently evaluating a forestry use case, and there is no request for a mobile app. However, I believe that a mobile app would be extremely useful, so I remembered SMASH and thought we could maybe give a hint, organize a workshop or write a manual and let them try it out. English wouldn't really work in Japan ... as you probably know well ;-)

**Comment by moovida** [comment]
Ahhh, so you were proposing to contribute translation from a coding perspective? 
If yes, that would be plain amazing!  I would be happy to help and review if that is the case. And we could start right away.

You are the second that brought up the issue, and both from Japan :-D So yes, would be happy to see this going on.

**Comment by dkastl** [comment]
Localization has been started in this branch: https://github.com/moovida/smash/tree/feature/internationalization
I tried the setup with Visual Code and it looked good.

Maybe some more considerations:

- [ ] What would be the default language? Can we detect the language of the device and fall back to English?
- [ ] Where to let the user configure the language?
- [ ] Do we need naming conventions for the naming of variables?

**Comment by moovida** [comment]
Hi Daniel, some comments from my side:

* the current branch works using the device's language. I would start this way and once I have a full second language I will implement a language selection setting in the app preferences/settings view.
* default language is English
* if you have ideas about naming conventions, I would be happy to hear them. Right now the only convention I used is that each variable for the translation should be prefixed either with the logical view it appears in or the class they can be found int. For example the currently available  strings all star with **main_XXXX** because they are in the main startup class. But I if you have experience, let's discuss.
* also I setup a localizely project with an open source profile. But I would start synchronisation only when we have something complete to check how it works.

**Comment by dkastl** [comment]
OK, I agree with the suggestions. I don't have much experience, just wanted to ask, if there is some convention. I saw that it always  starts with a prefix. I created a fork here and we can then send a pull request once Japanese is available: https://github.com/hyakumori/smash/tree/feature/internationalization

**Comment by moovida** [comment]
One more thing @dkastl . I just decided to merge the translation branch to master. It makes sense to make your interactions with it faster. The translation method has been chosen and I would directly create PR against master. That way I am hoping to gain a lower number or conflicting merges.

**Comment by dkastl** [comment]
OK, that's fine and makes things probably easier, if it doesn't cause problems.

**Comment by dkastl** [comment]
@moovida , just a question regarding the naming. You said before:

> For example the currently available strings all star with main_XXXX because they are in the main startup class. 

But rather than "class" name didn't you mean "file" name? 
Because all the strings are in the file `main.dart`, however the classes would be `class _WelcomeWidgetState` or `class _ProgressTileState` ... just to mention some examples.

**Comment by moovida** [comment]
Ah, yes, you are right. I am still not used to this way of handling dart code :-) Yes, I used the file name, which (apart of main) should represent a logical group of code.

**Comment by dkastl** [comment]
Actually I understood it like this and just later realized the file name is not the class name.

The problem that can occure with this naming is, that you may have identical file names in different subfolders. Or is there a convention that file names must be unique?

**Comment by moovida** [comment]
Ah, you are right. There is no convention actually. So it might happen. But I would be willing to change the file names of there are duplicated. So let's assume they are unique and if not, I will take action.

**Comment by dkastl** [comment]
OK, that's fine then. Otherwise we could have taken the folder name for example as a "pre-prefix" ... but names would get very long then. I took a quick look and right now file names don't seem to have duplicates.

**Comment by mbasa** [comment]
@moovida , hi.  I just finished the translation of SMASH and can now display Japanese strings throughout the application. I touched practically every source file in the process, and you might get overwhelmed  with the changes,  so you might want to take a look first here 

[hyakumori/smash/tree/gr-develop-i18n](https://github.com/hyakumori/smash/tree/gr-develop-i18n)

and give me an opinion before I create a formal pull request. 

Regards, 

Mario.

**Comment by moovida** [comment]
hi @mbasa , that is great news. And also good timing, because today I might be able to get through the review. 
I am scrolling through the changes of your branch. Could you make a formal PR, it makes it simpler for me to have a look and comment , if necessary.

**Comment by mbasa** [comment]
@moovida do you want me to make a new PR or just do a merge with Daniel's existing PR? Personally, I think it will be less confusing if a new PR is created.

**Comment by moovida** [comment]
Hi @mbasa , since I had time only this morning, I went on and created the PR of your branch. 
Everything looked good, only the gss_import merged with conflict and had some issues. I fixed them and will now push everything to master, so that it is simpler to work form here on.

I thought the PR from Daniel would no longer be valid and superseded by yours , so I didn't consider it. 

Is this ok for you?

**Comment by moovida** [comment]
@mbasa , sorry, I have to better explain. I merged your branch into my local and tested things. So when I push your branch will be merged. No PR was formally made :-)

**Comment by mbasa** [comment]
Ok, cool. Thanks. 

Yes, I suppose it will be best to close Daniel's PR since it is no longer valid as you mentioned.

**Comment by moovida** [comment]
Great, I will now push, so you can double-check if everything is valid.

**Comment by dkastl** [comment]
Closing mine is fine. It was more a test how (and if) it works.

**Comment by moovida** [comment]
Guess this can be closed. Localization is in place now.
