### ISSUE TITLE
Building with flutter 3 in release mode

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/smash#206]
I was wondering if someone is trying to build smash with flutter > 3.1 in release mode these days. Fact is that the location library is going mad and GPS is no longer working.

I opened a detailed issue here, since I thought the project would be more supported, but it seems there is in general no maintainance (we might have to look for something better):

https://github.com/Yukams/background_locator_fixed/issues/50

I would love to hear thoughts and possible solutions others might have found.

Once the django GSS is ready I would like to make finally make a new release, we have a ton of new stuff that never saw the light.

**Comment by sanak** [comment]
@moovida I made the following PR on the repository.
https://github.com/Yukams/background_locator_fixed/pull/53

Please try it (the last commit) when you have a time.

Related with the new release, I will check Japanese translation more and may add more changes (create PRs) in tomorrow and next Monday... 🙇‍♂️

**Comment by moovida** [comment]
Hi @sanak , thanks a lot for the PR. I just tested from your branch using:

```
  background_locator_2:
    git:
      url: https://github.com/sanak/background_locator_2.git
      ref: fix/callback-in-release-build
```
Even if it doesn't crash or show any error... the gps shows up red as if it was turned of. So response.
Were you able to try on a real device? Does it work for you?



Regarding translations, please take your time. There will be some time before we release and I will let you know before anyways.

**Comment by sanak** [comment]
@moovida Thanks for confirmation.
I haven't tried it on SMASH side, so I will take a look at it.
Also, thanks for caring about translation buffer. 🙇‍♂️

**Comment by moovida** [comment]
This should be closed, since we are using the branch of @sanak . Kudos.
