### ISSUE TITLE
project export. How to retrieve data

### ISSUE THREAD

**Issue by elisa-paperini** [geopaparazzi/smash#218]
In Geopaparazzi, when a project is exported to a KML file, the filled form's content appears in the file's structure, as shown in the image below (the orange part).
![Cattura_kml_geopap](https://user-images.githubusercontent.com/101557593/223413701-077e6fee-617e-4571-944f-5b91be682725.JPG)

The data contained in the notes are not visible when the same procedure is done with the same KML file project exported with Smash, as shown in the image below.
![Cattura_kml_smash](https://user-images.githubusercontent.com/101557593/223413703-7ce213cb-8c74-4370-a402-37cb1b27d363.JPG)

Is that normal? There is a way to visualize data as in Geopaparazzi KML exported file? I need the data in the KML file because I use it to create a CSV table with the collected documentation. Are there other ways to obtain a CSV file from the project?

Also when I imported the GPKG file on a QGIS project, all the data are visualized in a single column, but I would need a separated column for each field of the form. I think I'm doing something wrong, is there anyone who could help me?
![Cattura_gpkg_tabella_attributi](https://user-images.githubusercontent.com/101557593/223413693-b13ab62b-7531-4960-868f-8f22b25f91b1.JPG)
thank you

**Comment by moovida** [comment]
Hi @elisa-paperini , sorry for the late reply. It is true that the kml export has never been updated for the complete export of forms (geopaparazzi also exported the images into the kmz). To be honest I forgot about it, but I might give a look at it in near future (will let you know).

I am not sure I understand what you need exactly. Exporting a structure like a form into a csv will anyways flatten it (the way you see it in your screenshot above, so I am not sure what you mean. 
In the hortonmachine partnerproject we have a way to export form notes to shapefiles, separates by form type, i.e. every id of a form item is a field in the shapefile. And there will be as many shapefiles as there are form types. Does that help?

**Comment by elisa-paperini** [comment]
Hi @moovida, thanks a lot for your reply and your availability. If someone guides me I could try to update the kml export for the complete forms export. Just for learning.

I try to explain better, the aim is to obtain a file with a field for each key in the form (like the screenshot below), so we can do analysis and researches on it, at the moment we get it through some passages on the kml exported from Geopaparazzi. We have some troubles with the shapefile because of the 254 characters' text field limit, in the way you use in the hortomachine partnerproject, don't you have this problem?
![csv](https://user-images.githubusercontent.com/101557593/225590026-76dcdc98-832b-4f24-b1e3-ebf195d033ef.png)

**Comment by moovida** [comment]
> Hi @moovida, thanks a lot for your reply and your availability. 
> If someone guides me I could try to update the kml export for the 
> complete forms export. Just for learning.

Ohhhh, had I only known! I already fixed this. With the next release the export will be the same as in geopaparazzi (KMZ, not kml). So you will get the KMZ. But if you have abilities to do the changes, can I ask you to test the export with your data? I made a few test and images embedding seems to work nicely, but I would prefer some more testing.
That would mean that you would have to build the apk from the source code right now (if not, I can also send you one).

> I try to explain better, the aim is to obtain a file with a field for each key in 
> the form (like the screenshot below), so we can do analysis and researches on it, at the moment 
> we get it through some passages on the kml exported from Geopaparazzi. 
> We have some troubles with the shapefile because of the 254 characters' text
> field limit, in the way you use in the hortomachine partnerproject, don't you 
> have this problem?

No, we usually work with the GSS server, where the forms are kept in json format.
But if that is your only issue, one solution could be to change the hortonmachine to export into a geopackage, instead of shapefile. Would that work?

**Comment by elisa-paperini** [comment]
I tried to create the APK, but I can't. I get two errors on the android
studio (IDE error and SDK location not found) and I can't figure out how to
fix them in a short time. Sorry.

Yes, geopackage is better than a shapefile for us!

Thank you very much for your support.

Il giorno gio 16 mar 2023 alle ore 17:11 Andrea Antonello <
***@***.***> ha scritto:

**Comment by moovida** [comment]
Ok, I placed a test build here: https://we.tl/t-F1BudTxs3z

Let me know how the kmz export goes.

**Comment by elisa-paperini** [comment]
I can't enter the application menu. There is an error that says archiving permission is mandatory to utilize the application, but I have already authorized the archiving permission. Also from phone settings, I see that the application is allowed to access the archive.

**Comment by elisa-paperini** [comment]
I'm using the version 9
