### ISSUE TITLE
Oddities with translations

### ISSUE THREAD

**Issue by moovida** [geopaparazzi/smash#221]
@sanak , I am experiencing issues with missing translations and parts of the application that do not work if the language is not present in some subproject.

One example is that part of the forms do not work, probably since translation has been introduced in smashlibs. I noticed that there is also no weblate project for that, probably because there is just one message translate.

What is the best practice for that? 

Also, do you have any idea why the engine doe snot fallback on the English version, if the current locale is not available?
Do we have to generate an empty file for any missing language?

**Comment by sanak** [comment]
@moovida (CC: @dkastl, @smellman)
Thanks for feedback about missing translation issue.

I don't know what is the cause and how to fix that, but I will try to check it later.
(I became a bit busy for other project, so my check will not be so fast...)

And thanks for the following commits which seem to cover above issue.
- https://github.com/geopaparazzi/smashlibs/commit/0122c63f1e739151dcd848e7e9e346e9f88fc827#diff-5ed023dcb87cd0c87016b4cdb87fd244db8283f674246264591c7cd50ca92243
- https://github.com/geopaparazzi/smashlibs/commit/4b80b1de4f0d8cae405cac4427b24647d6061733

---

> I noticed that there is also no weblate project for that, probably because there is just one message translate.

About this, I don't have admin access to hosted weblate's project (https://hosted.weblate.org/projects/smash/).
So, if possible, creating a new `smash-libs` project on weblate is helpful. (CC: @dkastl)
