### ISSUE TITLE
Update OSM tile URL

### ISSUE THREAD

**Issue by licaon-kter** [geopaparazzi/smash#229]
ref: I guess https://github.com/geopaparazzi/smash/blob/version_1.7.6%2B68_fdroid/lib/eu/hydrologis/smash/maps/layers/types/tiles.dart#L106 maybe more?

ref: https://github.com/openstreetmap/operations/issues/737

**Comment by moovida** [comment]
Done, thanks!

**Comment by danieldegroot2** [comment]
@moovida what about [this code](https://github.com/geopaparazzi/smash/blob/71d13d32a2021b91e7bfe9cb8d2e4c91c335d407/lib/eu/hydrologis/smash/widgets/log_properties.dart#L519)?

**Comment by moovida** [comment]
@danieldegroot2 , that definitely slipped through my radar. Thank you!

**Comment by moovida** [comment]
done
