### ISSUE TITLE
Zoom level indicator auto-update

### ISSUE THREAD

**Issue by opk12** [geopaparazzi/smash#243]
Do I understand correctly that the number at the bottom right is the zoom level? It does not change, when I pinch the slippy map to zoom in or zoom out. It should auto-update instead. But then I press the blue arrow at the bottom right (toggle menu bar icons) and it gets updated.

**Comment by moovida** [comment]
Hi @opk12 , yes it is the zoomlevel. Up to some time ago it was not possible in the flutter map lib to catch the pinch zoom event, so the number it connected to the zoom in and out buttons. 
I just saw that now some more events:

* MapEventDoubleTapZoom
* MapEventScrollWheelZoom

but still no pinch event. 
Adding these in the meanwhile to fix at least the double tap and the wheel scroll for desktop versions.

**Comment by opk12** [comment]
Thank you. Is it [fleaflet/flutter_map](https://github.com/fleaflet/flutter_map)? If so, I opened [this ticket](https://github.com/fleaflet/flutter_map/issues/1732) for a generic zoom event API, which seems not to exist indeed in the [class list](https://pub.dev/documentation/flutter_map/latest/flutter_map/flutter_map-library.html#MapEvent), if it can help somehow

**Comment by moovida** [comment]
Great, thanks. When the event will be implemented, we can also move it to smash.

**Comment by moovida** [comment]
Hi @opk12 , for a different reason I ended up checking the MapEvents once more and found that there is a multi finger event that is redirected into a MapEventMove. So listening to that one made the zoom indicator finally work. I want to do some more testing on this, but seems to work nicely. Closing this for now.

**Comment by opk12** [comment]
Thank you. FYI There's a gesture API restructuring in the works. https://github.com/fleaflet/flutter_map/issues/1715

**Comment by moovida** [comment]
Yep, thanks, I saw this and am not looking forward to migrate to flutter_map 5. Already 4 has been a pain. :-)
