### ISSUE TITLE
Option not to keep GPS logging active in the background

### ISSUE THREAD

**Issue by opk12** [geopaparazzi/smash#244]
I do my surveys when I do errands or am a tourist. I frequently lock the phone, or switch the focus to the web browser / chat. I'm unconstrained by time and not coordinated with other mappers.

According to the notification, the app registers the location even when it is in the background. So it is consuming battery unnecessarily. I only need the location when I take the phone out of the pocket and place a note. What about an option to only log the location when the app is in foreground?

For example, OsmAnd does not have the active service / permanent notification, by default. When put again in foreground, it shows the old location in grey. Then it updates the location quickly (just 2-3 seconds). I can turn on the GPX track registration mode, to keep the location always on (with permanent notification).

**Comment by moovida** [comment]
Hi @opk12 , I looked into this, but it seems that it can't be chosen as an option in the gps lib we use. I am afraid as for now this can't be done. If an option pops up though, I will be happy to bring this into a setting. Feel free to reopen the issue if you find a way.

**Comment by opk12** [comment]
Thank you for looking into it.

For the future myself, it's `yukams.app.background_locator_2` https://github.com/Yukams/background_locator_fixed
