### ISSUE TITLE
Wikimedia Maps is unavailable

### ISSUE THREAD

**Issue by opk12** [geopaparazzi/smash#245]
Public usage of Wikimedia Maps was disabled in 2020, per [announcement](https://lists.wikimedia.org/hyperkitty/list/maps-l@lists.wikimedia.org/message/SNS54LBGFB646LPZ25M2SSDVNPNJ7OLC/) and [ticket](https://phabricator.wikimedia.org/T261424), and is now prohibited by the [Terms of Use](https://foundation.wikimedia.org/wiki/Policy:Maps_Terms_of_Use#Using_maps_in_third-party_services). It should be removed from the online sources.

**Comment by moovida** [comment]
Hi @opk12 , thanks a lot for this heads up, I will remove it from the list. Should be able to work on this soon.

**Comment by moovida** [comment]
done
