### ISSUE TITLE
Adding an online source hides the predefined online sources

### ISSUE THREAD

**Issue by opk12** [geopaparazzi/smash#246]
1. Open the Layers list.
2. Open the Online Sources Catalog. The predefined sources are listed.
3. Add a source.
4. Now the list shows the new source, but not the predefined sources.

I am using version 1.7.6 from F-droid, if it can help.

**Comment by moovida** [comment]
Thanks for reporting, that is odd. Will look into it.

**Comment by moovida** [comment]
This is solved with the fix of #247
