### ISSUE TITLE
Recover predefined online source

### ISSUE THREAD

**Issue by opk12** [geopaparazzi/smash#247]
I accidentally clicked on the wrong button and deleted Esri from the predefined online sources list. There should be a way to make the entry again (without entering the data manually, or importing).

**Comment by moovida** [comment]
I think you can do that by removing all sources (then the default reload). But I agree that is no good user experience.

**Comment by moovida** [comment]
This has now been solved with an "add TMS from defaults" in the right drawer of the catalog. That way one can add a source just if they want to.
