### ISSUE TITLE
"type"="integer" and "islabel"="true" incompatible in Android 14

### ISSUE THREAD

**Issue by elisa-paperini** [geopaparazzi/smash#263]
Hi,

While developing a new form for complex notes, I noticed that in Android 14 it is no longer possible to enter a number as a label, but only data in string format.
If an integer is entered as a label, the application crashes on the note form screen, does not allow you to return to the map, and does not save the data. This was a useful feature in previous versions.

If anyone can point me in the right direction, I am happy to try and fix this.

**Comment by moovida** [comment]
Hi Elisa, I am not sure what you mean. You mean that it crashes if isLabel is set to a non string field? That would be a huge bug.

BTW, are you using the integrated formbuilder? (end of https://www.youtube.com/watch?v=lRXou2QnE3s)

**Comment by elisa-paperini** [comment]
> Hi Elisa, I am not sure what you mean. You mean that it crashes if isLabel is set to a non string field? That would be a huge bug.
Yes, exactly. If I set an integer field to isLabel, it crashes. I tried it on two different phones, both of them Android 14.

> BTW, are you using the integrated formbuilder? (end of https://www.youtube.com/watch?v=lRXou2QnE3s)
No, I am used to modifying the tags.json file. I will try it.

**Comment by elisa-paperini** [comment]
I cannot access the server. I've followed the tutorials (https://hub.docker.com/r/moovida/gss and https://www.geopaparazzi.org/gss/index.html) and everything seems to be working properly. When I log in to localhost it says that the server is up and running, but it doesn't show the Smash login page and I don't understand what I'm doing wrong.

**Comment by moovida** [comment]
Hi @elisa-paperini , sorry for being so late, this is not a good period for voluntary work :-)

I finally found the time to update the GSS server to the latest version, as used by the Region Piemonte, which sponsored all the latest enhancements.

There is a tutorial, currently served as a readme: https://github.com/geopaparazzi/GSS/blob/master/README.md
that should allow you to have a GSS running in really few time.

The new server is now (and will be) available at this docker bug url: https://hub.docker.com/r/moovida/gss-docker

I hope that solves your issues. If not, please let me know.


Regarding the actual objective of this issue,  when you write: "If anyone can point me in the right direction, I am happy to try and fix this." you mean that you could be able to debug that with an IDE on your device? I would be more than happy to give you some input to that.
