### ISSUE TITLE
GPS info frame

### ISSUE THREAD

**Issue by opk12** [geopaparazzi/smash#264]
The blue frame with the GPS info, that appears when long-tapping the scope, stays open for a few seconds after that I have read the wanted number. What about having it auto-close when the user taps elsewhere, or taps the scope again?

**Comment by moovida** [comment]
I went through various changes in this. At the end I decided that the fact that a toast can be hidden by dragging it downwards,  would be a good compromise. What do you think?

**Comment by opk12** [comment]
Sure, if recognizable by the distinctive look of the [bottom sheet](https://m3.material.io/components/bottom-sheets/overview), or another GUI pattern with a different appearance than a toast (which auto-closes) and a tooltip (which closes when clicking).

**Comment by moovida** [comment]
Done
