### ISSUE TITLE
New icon of the App? 

### ISSUE THREAD

**Issue by HuggeK** [geopaparazzi/smash#274]
Have the icon changed of SMASH? The [geopaparazzi logo](https://avatars.githubusercontent.com/u/6114834?s=200&v=4), [old logo on the OSM wiki.](https://wiki.openstreetmap.org/wiki/SMASH)

Thinking of the [wiki userbox ](https://wiki.openstreetmap.org/wiki/Template:User_SMASH)on the OSM wiki.

**Comment by moovida** [comment]
Hi @HuggeK , sorry for the late reply, just back from vacation. 
The smash logo is still the same: https://github.com/geopaparazzi/smash/blob/master/android/app/src/main/res/drawable/splash.png

It is different from the retired geopaparazzi (which smash replaces and is compatible with) app logo.
