### ISSUE TITLE
Images should not be in exported Geopackages

### ISSUE THREAD

**Issue by AndrewM-** [geopaparazzi/smash#287]
Most of the time, I want to email or sync a geopackage back to the GIS department.  They do not need or even want the photos.  They only need to make maps of where I have been and from the data that I have collected.  I am using TerraFlex for structured data collection and it syncs data including photos back to the cloud.  If the cellular network is patchy as it is in most of Australia, we get sync failures or synchronisation takes a very long time.  For this reason, I would like geopackages to remain small and any photos to be exported to a folder.  

As of right now, I am not sure how to view photos embedded in a sqlite database within QGIS.  I would have to export them first and then import the geotagged photos into QGIS.  I am not sure that I can use photos within a geopackage directly.

As least provide the option of exporting a geopackage with/without photos.

**Comment by AndrewM-** [comment]
More thoughts on this matter.  I often do multiday surveys and need a lightweight way to back up my data.  I suppose the best way is to copy the gpap file over at the end of each day, but the gpap file is quite large, when it contains lots of photos.  I almost need a lightweight alternative so that I can email or sync my tracks and data points back to the office.

**Comment by moovida** [comment]
Hi @AndrewM- , even if I am not able to work on this right now, I am following these issues and thinking about them.

While I can imagine to add an option to export to geopackage without images, I see the second issue you mention it more difficult.
When you say, you do a lightweight survey, what do you mean? Once the survey is done with images, it is difficult to send it without them.

**Comment by AndrewM-** [comment]
@moovida Having the ability to export a geopackage without images would be great as this is a lightweight option.  I export the images to a folder and can easily sync the image folder, thereby avoiding doubling up of image exports.  So managing images is not hard, it only getting the rest of the geographic data that is at the heart of my request.  There is no rush.

**Comment by moovida** [comment]
Ok, that one looks like a feasible option to me.

**Comment by AndrewM-** [comment]
Just a late thought.  The image export should also be to a fixed folder, rather than to a new folder each time.  For example, if a project was called 'Sydney', then the image export folder should be called 'Sydney/images'
It is then relatively easy to make a report that links content from the geopackage with the images.  Below is an example.  I have over 500 fence points, collected over a period of three weeks.  You can imagine, that I want to check data collection each night to make sure that it is going well.

![FencingReport](https://github.com/user-attachments/assets/6c35ee55-c924-4630-8146-6257f3b50129)

**Comment by moovida** [comment]
I have finally been able to work on this. 
I find the idea of exporting into a project folder really good, not sure why it never occurred to me. :-)

I also converted the export to geopackage into a page where you can select if you want to export with or without images.

Will go into the next release
