### ISSUE TITLE
Turn GPS off on iphone7 do not work

### ISSUE THREAD

**Issue by silviafranceschi** [geopaparazzi/smash#47]
The Turn GPS off  command do not work in iphone7, it works correctly on iphone XS.
Simply it doesn't do anything, if you click the option in the menu it shows immediately the other option Turn GPS on, but after a second it comes back to Turn GPS off  and in fact the GPS continues to work.
This problems occured only when I overwrite the version of SMASH, if I delete the old version and reinstall the new one the button works.

**Comment by moovida** [comment]
Not sure if this is still an issue. Closing in the meanwhile. In case just reopen.
