### ISSUE TITLE
about the editing work flow 

### ISSUE THREAD

**Issue by skylning** [geopaparazzi/smash#98]
when create a new feature(polygon or polyline),the project  add a 3 points area or 2 points line,then modify it,in my mind ,may be  the edit flow  is follow like arcmap edit flow:
1.set the current edit layer
2.tap on map add new feature and it,s points by every tap
3.select feature to update

if  the edit flow add the snap model....

**Comment by moovida** [comment]
I am not sure I understand. Are you proposing a better workflow, right? 

I agree with you that the current method is not very nice. The reason it is like that at the moment is the usual time I am missing. To create the proper workflow internally I have to make the layer a point layer, after the second a line and after the third a polygon (in case of polygon). That was the main reason and the missing time. But I agree that it is not nice. 

As time comes I hope to be able to fix this.

**Comment by skylning** [comment]
yes, i hope a better edit workflow.

i want the edit workflow as :
1.when i click the edit button,enable the edit session and pop a layer list to set current edit layer,disiable edit by click the button again;
2.add a new button to add new features;
3.edit exist feature by maplongtap to select feature
4.before save the edit result to db,i will check the feature attributes and modify attributes,if the feature is newer.then add new feature to db,else update exist feature in db.
